services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8001"
    networks:
      - app-network
    depends_on:
      - mariadb
    restart: always

  ui:
    build:
      context: ./ui
      dockerfile: src/Dockerfile
    expose:
      - "80"
    networks:
      - app-network

  centrifugo:
    image: centrifugo/centrifugo:v5.4
    volumes:
      - ./charts/centrifugo.json:/centrifugo/config.json
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./charts/prod.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
      - ui
      - centrifugo
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: neviss-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mamad
      MYSQL_DATABASE: pixel
      MYSQL_USER: mamad
      MYSQL_PASSWORD: mamad
    networks:
      - app-network
    volumes:
      - pixel_mariadb_data:/var/lib/mysql

  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: neviss-redis-stack
    networks:
      - app-network
    volumes:
      - pixel_redis_stack_data:/data

networks:
  app-network:
    driver: bridge
volumes:
  pixel_mariadb_data:
  pixel_redis_stack_data: