services:
  centrifugal:
    image: centrifugo/centrifugo:v5.4
    network_mode: host
    expose:
      - 8000
    volumes:
      - ./charts/centrifugo.json:/etc/centrifugo/config.json
    command: centrifugo --config /etc/centrifugo/config.json

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mamad
      MYSQL_DATABASE: tonference
      MYSQL_USER: mamad
      MYSQL_PASSWORD: mamad
    network_mode: host
    volumes:
      - tonference_mariadb_data:/var/lib/mysql

volumes:
  tonference_mariadb_data: