// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mhrlife/tonference/internal/ent/room"
	"github.com/mhrlife/tonference/internal/ent/user"
)

// RoomCreate is the builder for creating a Room entity.
type RoomCreate struct {
	config
	mutation *RoomMutation
	hooks    []Hook
}

// SetShortID sets the "short_id" field.
func (rc *RoomCreate) SetShortID(s string) *RoomCreate {
	rc.mutation.SetShortID(s)
	return rc
}

// SetNillableShortID sets the "short_id" field if the given value is not nil.
func (rc *RoomCreate) SetNillableShortID(s *string) *RoomCreate {
	if s != nil {
		rc.SetShortID(*s)
	}
	return rc
}

// SetStatus sets the "status" field.
func (rc *RoomCreate) SetStatus(r room.Status) *RoomCreate {
	rc.mutation.SetStatus(r)
	return rc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rc *RoomCreate) SetNillableStatus(r *room.Status) *RoomCreate {
	if r != nil {
		rc.SetStatus(*r)
	}
	return rc
}

// SetMaxParticipants sets the "max_participants" field.
func (rc *RoomCreate) SetMaxParticipants(i int8) *RoomCreate {
	rc.mutation.SetMaxParticipants(i)
	return rc
}

// SetNillableMaxParticipants sets the "max_participants" field if the given value is not nil.
func (rc *RoomCreate) SetNillableMaxParticipants(i *int8) *RoomCreate {
	if i != nil {
		rc.SetMaxParticipants(*i)
	}
	return rc
}

// SetPermissionVideo sets the "permission_video" field.
func (rc *RoomCreate) SetPermissionVideo(rv room.PermissionVideo) *RoomCreate {
	rc.mutation.SetPermissionVideo(rv)
	return rc
}

// SetNillablePermissionVideo sets the "permission_video" field if the given value is not nil.
func (rc *RoomCreate) SetNillablePermissionVideo(rv *room.PermissionVideo) *RoomCreate {
	if rv != nil {
		rc.SetPermissionVideo(*rv)
	}
	return rc
}

// SetPermissionAudio sets the "permission_audio" field.
func (rc *RoomCreate) SetPermissionAudio(ra room.PermissionAudio) *RoomCreate {
	rc.mutation.SetPermissionAudio(ra)
	return rc
}

// SetNillablePermissionAudio sets the "permission_audio" field if the given value is not nil.
func (rc *RoomCreate) SetNillablePermissionAudio(ra *room.PermissionAudio) *RoomCreate {
	if ra != nil {
		rc.SetPermissionAudio(*ra)
	}
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *RoomCreate) SetCreatedAt(t time.Time) *RoomCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RoomCreate) SetNillableCreatedAt(t *time.Time) *RoomCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *RoomCreate) SetUpdatedAt(t time.Time) *RoomCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *RoomCreate) SetNillableUpdatedAt(t *time.Time) *RoomCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// AddAdminIDs adds the "admins" edge to the User entity by IDs.
func (rc *RoomCreate) AddAdminIDs(ids ...int64) *RoomCreate {
	rc.mutation.AddAdminIDs(ids...)
	return rc
}

// AddAdmins adds the "admins" edges to the User entity.
func (rc *RoomCreate) AddAdmins(u ...*User) *RoomCreate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return rc.AddAdminIDs(ids...)
}

// Mutation returns the RoomMutation object of the builder.
func (rc *RoomCreate) Mutation() *RoomMutation {
	return rc.mutation
}

// Save creates the Room in the database.
func (rc *RoomCreate) Save(ctx context.Context) (*Room, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RoomCreate) SaveX(ctx context.Context) *Room {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RoomCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RoomCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RoomCreate) defaults() {
	if _, ok := rc.mutation.ShortID(); !ok {
		v := room.DefaultShortID()
		rc.mutation.SetShortID(v)
	}
	if _, ok := rc.mutation.Status(); !ok {
		v := room.DefaultStatus
		rc.mutation.SetStatus(v)
	}
	if _, ok := rc.mutation.MaxParticipants(); !ok {
		v := room.DefaultMaxParticipants
		rc.mutation.SetMaxParticipants(v)
	}
	if _, ok := rc.mutation.PermissionVideo(); !ok {
		v := room.DefaultPermissionVideo
		rc.mutation.SetPermissionVideo(v)
	}
	if _, ok := rc.mutation.PermissionAudio(); !ok {
		v := room.DefaultPermissionAudio
		rc.mutation.SetPermissionAudio(v)
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := room.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := room.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RoomCreate) check() error {
	if _, ok := rc.mutation.ShortID(); !ok {
		return &ValidationError{Name: "short_id", err: errors.New(`ent: missing required field "Room.short_id"`)}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Room.status"`)}
	}
	if v, ok := rc.mutation.Status(); ok {
		if err := room.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Room.status": %w`, err)}
		}
	}
	if _, ok := rc.mutation.MaxParticipants(); !ok {
		return &ValidationError{Name: "max_participants", err: errors.New(`ent: missing required field "Room.max_participants"`)}
	}
	if _, ok := rc.mutation.PermissionVideo(); !ok {
		return &ValidationError{Name: "permission_video", err: errors.New(`ent: missing required field "Room.permission_video"`)}
	}
	if v, ok := rc.mutation.PermissionVideo(); ok {
		if err := room.PermissionVideoValidator(v); err != nil {
			return &ValidationError{Name: "permission_video", err: fmt.Errorf(`ent: validator failed for field "Room.permission_video": %w`, err)}
		}
	}
	if _, ok := rc.mutation.PermissionAudio(); !ok {
		return &ValidationError{Name: "permission_audio", err: errors.New(`ent: missing required field "Room.permission_audio"`)}
	}
	if v, ok := rc.mutation.PermissionAudio(); ok {
		if err := room.PermissionAudioValidator(v); err != nil {
			return &ValidationError{Name: "permission_audio", err: fmt.Errorf(`ent: validator failed for field "Room.permission_audio": %w`, err)}
		}
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Room.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Room.updated_at"`)}
	}
	return nil
}

func (rc *RoomCreate) sqlSave(ctx context.Context) (*Room, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RoomCreate) createSpec() (*Room, *sqlgraph.CreateSpec) {
	var (
		_node = &Room{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(room.Table, sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.ShortID(); ok {
		_spec.SetField(room.FieldShortID, field.TypeString, value)
		_node.ShortID = value
	}
	if value, ok := rc.mutation.Status(); ok {
		_spec.SetField(room.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := rc.mutation.MaxParticipants(); ok {
		_spec.SetField(room.FieldMaxParticipants, field.TypeInt8, value)
		_node.MaxParticipants = value
	}
	if value, ok := rc.mutation.PermissionVideo(); ok {
		_spec.SetField(room.FieldPermissionVideo, field.TypeEnum, value)
		_node.PermissionVideo = value
	}
	if value, ok := rc.mutation.PermissionAudio(); ok {
		_spec.SetField(room.FieldPermissionAudio, field.TypeEnum, value)
		_node.PermissionAudio = value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(room.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.SetField(room.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := rc.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   room.AdminsTable,
			Columns: room.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RoomCreateBulk is the builder for creating many Room entities in bulk.
type RoomCreateBulk struct {
	config
	err      error
	builders []*RoomCreate
}

// Save creates the Room entities in the database.
func (rcb *RoomCreateBulk) Save(ctx context.Context) ([]*Room, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Room, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RoomCreateBulk) SaveX(ctx context.Context) []*Room {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RoomCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RoomCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
