// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mhrlife/tonference/internal/ent/room"
	"github.com/mhrlife/tonference/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescShortID is the schema descriptor for short_id field.
	roomDescShortID := roomFields[0].Descriptor()
	// room.DefaultShortID holds the default value on creation for the short_id field.
	room.DefaultShortID = roomDescShortID.Default.(func() string)
	// roomDescMaxParticipants is the schema descriptor for max_participants field.
	roomDescMaxParticipants := roomFields[2].Descriptor()
	// room.DefaultMaxParticipants holds the default value on creation for the max_participants field.
	room.DefaultMaxParticipants = roomDescMaxParticipants.Default.(int8)
	// roomDescCreatedAt is the schema descriptor for created_at field.
	roomDescCreatedAt := roomFields[5].Descriptor()
	// room.DefaultCreatedAt holds the default value on creation for the created_at field.
	room.DefaultCreatedAt = roomDescCreatedAt.Default.(func() time.Time)
	// roomDescUpdatedAt is the schema descriptor for updated_at field.
	roomDescUpdatedAt := roomFields[6].Descriptor()
	// room.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	room.DefaultUpdatedAt = roomDescUpdatedAt.Default.(func() time.Time)
	// room.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	room.UpdateDefaultUpdatedAt = roomDescUpdatedAt.UpdateDefault.(func() time.Time)
}
