// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PixelsColumns holds the columns for the "pixels" table.
	PixelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "color", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PixelsTable holds the schema information for the "pixels" table.
	PixelsTable = &schema.Table{
		Name:       "pixels",
		Columns:    PixelsColumns,
		PrimaryKey: []*schema.Column{PixelsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "game_id", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_game_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
			},
		},
	}
	// UserPixelsColumns holds the columns for the "user_pixels" table.
	UserPixelsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "pixel_id", Type: field.TypeInt},
	}
	// UserPixelsTable holds the schema information for the "user_pixels" table.
	UserPixelsTable = &schema.Table{
		Name:       "user_pixels",
		Columns:    UserPixelsColumns,
		PrimaryKey: []*schema.Column{UserPixelsColumns[0], UserPixelsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_pixels_user_id",
				Columns:    []*schema.Column{UserPixelsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_pixels_pixel_id",
				Columns:    []*schema.Column{UserPixelsColumns[1]},
				RefColumns: []*schema.Column{PixelsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PixelsTable,
		UsersTable,
		UserPixelsTable,
	}
)

func init() {
	UserPixelsTable.ForeignKeys[0].RefTable = UsersTable
	UserPixelsTable.ForeignKeys[1].RefTable = PixelsTable
}
