// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HypesColumns holds the columns for the "hypes" table.
	HypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount_remaining", Type: field.TypeInt},
		{Name: "max_hype", Type: field.TypeInt},
		{Name: "last_updated_at", Type: field.TypeTime},
		{Name: "hype_per_minute", Type: field.TypeInt, Default: 2},
		{Name: "user_hype", Type: field.TypeInt64, Unique: true},
	}
	// HypesTable holds the schema information for the "hypes" table.
	HypesTable = &schema.Table{
		Name:       "hypes",
		Columns:    HypesColumns,
		PrimaryKey: []*schema.Column{HypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "hypes_users_hype",
				Columns:    []*schema.Column{HypesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PixelsColumns holds the columns for the "pixels" table.
	PixelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "color", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_pixels", Type: field.TypeInt64, Nullable: true},
	}
	// PixelsTable holds the schema information for the "pixels" table.
	PixelsTable = &schema.Table{
		Name:       "pixels",
		Columns:    PixelsColumns,
		PrimaryKey: []*schema.Column{PixelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pixels_users_pixels",
				Columns:    []*schema.Column{PixelsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "game_id", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_game_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HypesTable,
		PixelsTable,
		UsersTable,
	}
)

func init() {
	HypesTable.ForeignKeys[0].RefTable = UsersTable
	PixelsTable.ForeignKeys[0].RefTable = UsersTable
}
