// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nevissGo/ent/hype"
	"nevissGo/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Hype is the model entity for the Hype schema.
type Hype struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AmountRemaining holds the value of the "amount_remaining" field.
	AmountRemaining int `json:"amount_remaining,omitempty"`
	// MaxHype holds the value of the "max_hype" field.
	MaxHype int `json:"max_hype,omitempty"`
	// LastUpdatedAt holds the value of the "last_updated_at" field.
	LastUpdatedAt time.Time `json:"last_updated_at,omitempty"`
	// HypePerMinute holds the value of the "hype_per_minute" field.
	HypePerMinute int `json:"hype_per_minute,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HypeQuery when eager-loading is set.
	Edges        HypeEdges `json:"edges"`
	user_hype    *int64
	selectValues sql.SelectValues
}

// HypeEdges holds the relations/edges for other nodes in the graph.
type HypeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HypeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Hype) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hype.FieldID, hype.FieldAmountRemaining, hype.FieldMaxHype, hype.FieldHypePerMinute:
			values[i] = new(sql.NullInt64)
		case hype.FieldLastUpdatedAt:
			values[i] = new(sql.NullTime)
		case hype.ForeignKeys[0]: // user_hype
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Hype fields.
func (h *Hype) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			h.ID = int(value.Int64)
		case hype.FieldAmountRemaining:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_remaining", values[i])
			} else if value.Valid {
				h.AmountRemaining = int(value.Int64)
			}
		case hype.FieldMaxHype:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_hype", values[i])
			} else if value.Valid {
				h.MaxHype = int(value.Int64)
			}
		case hype.FieldLastUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated_at", values[i])
			} else if value.Valid {
				h.LastUpdatedAt = value.Time
			}
		case hype.FieldHypePerMinute:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hype_per_minute", values[i])
			} else if value.Valid {
				h.HypePerMinute = int(value.Int64)
			}
		case hype.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_hype", value)
			} else if value.Valid {
				h.user_hype = new(int64)
				*h.user_hype = int64(value.Int64)
			}
		default:
			h.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Hype.
// This includes values selected through modifiers, order, etc.
func (h *Hype) Value(name string) (ent.Value, error) {
	return h.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Hype entity.
func (h *Hype) QueryUser() *UserQuery {
	return NewHypeClient(h.config).QueryUser(h)
}

// Update returns a builder for updating this Hype.
// Note that you need to call Hype.Unwrap() before calling this method if this Hype
// was returned from a transaction, and the transaction was committed or rolled back.
func (h *Hype) Update() *HypeUpdateOne {
	return NewHypeClient(h.config).UpdateOne(h)
}

// Unwrap unwraps the Hype entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (h *Hype) Unwrap() *Hype {
	_tx, ok := h.config.driver.(*txDriver)
	if !ok {
		panic("ent: Hype is not a transactional entity")
	}
	h.config.driver = _tx.drv
	return h
}

// String implements the fmt.Stringer.
func (h *Hype) String() string {
	var builder strings.Builder
	builder.WriteString("Hype(")
	builder.WriteString(fmt.Sprintf("id=%v, ", h.ID))
	builder.WriteString("amount_remaining=")
	builder.WriteString(fmt.Sprintf("%v", h.AmountRemaining))
	builder.WriteString(", ")
	builder.WriteString("max_hype=")
	builder.WriteString(fmt.Sprintf("%v", h.MaxHype))
	builder.WriteString(", ")
	builder.WriteString("last_updated_at=")
	builder.WriteString(h.LastUpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("hype_per_minute=")
	builder.WriteString(fmt.Sprintf("%v", h.HypePerMinute))
	builder.WriteByte(')')
	return builder.String()
}

// Hypes is a parsable slice of Hype.
type Hypes []*Hype
