// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldGameID holds the string denoting the game_id field in the database.
	FieldGameID = "game_id"
	// EdgePixels holds the string denoting the pixels edge name in mutations.
	EdgePixels = "pixels"
	// Table holds the table name of the user in the database.
	Table = "users"
	// PixelsTable is the table that holds the pixels relation/edge. The primary key declared below.
	PixelsTable = "user_pixels"
	// PixelsInverseTable is the table name for the Pixel entity.
	// It exists in this package in order to avoid circular dependency with the "pixel" package.
	PixelsInverseTable = "pixels"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldDisplayName,
	FieldGameID,
}

var (
	// PixelsPrimaryKey and PixelsColumn2 are the table columns denoting the
	// primary key for the pixels relation (M2M).
	PixelsPrimaryKey = []string{"user_id", "pixel_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByGameID orders the results by the game_id field.
func ByGameID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameID, opts...).ToFunc()
}

// ByPixelsCount orders the results by pixels count.
func ByPixelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPixelsStep(), opts...)
	}
}

// ByPixels orders the results by pixels terms.
func ByPixels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPixelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPixelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PixelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, PixelsTable, PixelsPrimaryKey...),
	)
}
