// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Hype is the predicate function for hype builders.
type Hype func(*sql.Selector)

// Pixel is the predicate function for pixel builders.
type Pixel func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
